<?php
require_once '../includes/functions.php';
requireUserLogin();

$user = getCurrentUser();
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mystery Box - <?php echo SITE_NAME; ?></title>
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    <link rel="stylesheet" href="/assets/css/custom.css">
</head>

<body class="bg-gradient-to-br from-purple-600 via-blue-600 to-indigo-800 min-h-screen">
    <!-- Navigation -->
    <nav class="bg-white/10 backdrop-blur-lg border-b border-white/20 hide-full">
        <div class="container mx-auto px-4 py-4">
            <div class="flex justify-between items-center">
                <h1 class="text-2xl font-bold text-white">
                    <i class="fas fa-gift text-yellow-400"></i>
                    <?php echo SITE_NAME; ?>
                </h1>
                <div class="flex items-center space-x-4">
                    <a href="dashboard.php" class="text-white hover:text-yellow-400 transition duration-300">
                        <i class="fas fa-home mr-2"></i>Dashboard
                    </a>
                    <a href="history.php" class="text-white hover:text-yellow-400 transition duration-300">
                        <i class="fas fa-history mr-2"></i>History
                    </a>
                    <span class="text-white">Welcome, <?php echo htmlspecialchars($user['name']); ?>!</span>
                    <a href="/auth/logout.php" class="bg-red-500 hover:bg-red-600 text-white px-4 py-2 rounded-lg transition duration-300">
                        <i class="fas fa-sign-out-alt mr-2"></i>Logout
                    </a>
                </div>
            </div>
        </div>
    </nav>

    <div class="container mx-auto px-4 py-8">
        <!-- Header -->
        <div class="text-center mb-8 hide-full">
            <h2 class="text-5xl font-bold text-white mb-4 float">
                📦 Mystery Box
            </h2>
            <p class="text-xl text-blue-100">Open a mystery box and discover what's inside!</p>
        </div>

        <!-- Game Area -->
        <div class="max-w-7xl mx-auto">
            <div class="flex flex-col gap-8">
                <!-- Box Grid Section -->
                <div class="text-center">
                    <div class="mb-10 mt-3">
                        <button class="rounded-lg bg-blue-300/50 px-5 py-2 hover:bg-blue-400/50 duration-300 full-screen"><i class="fa-solid fa-expand"></i> Full Screen</button>
                    </div>

                    <h3 class="text-2xl font-bold text-white mb-6">Choose Your Mystery Box!</h3>

                    <!-- 5x3 Grid of Mystery Boxes -->
                    <div class="grid grid-cols-5 gap-8 mb-8 max-w-7xl mx-auto" id="boxGrid">
                        <!-- Boxes will be generated by JavaScript -->
                    </div>

                    <div class="mt-6 text-blue-100">
                        <p class="text-sm">Click any box to open it and discover your prize!</p>
                        <p class="text-xs mt-2 opacity-75">Each box contains a random prize with different odds</p>
                    </div>
                </div>

                <!-- Info Section -->
                <div class="bg-white/10 backdrop-blur-lg rounded-2xl p-8 border border-white/20">
                    <h3 class="text-2xl font-bold text-white mb-6">
                        <i class="fas fa-info-circle text-blue-400 mr-2"></i>
                        How It Works
                    </h3>

                    <div class="space-y-4 text-blue-100">
                        <div class="flex items-start">
                            <div class="bg-green-500 text-white rounded-full w-8 h-8 flex items-center justify-center font-bold mr-4 mt-1">1</div>
                            <div>
                                <h4 class="font-semibold text-white">Click to Open</h4>
                                <p>Click the mystery box or the "Open Box" button</p>
                            </div>
                        </div>

                        <div class="flex items-start">
                            <div class="bg-green-500 text-white rounded-full w-8 h-8 flex items-center justify-center font-bold mr-4 mt-1">2</div>
                            <div>
                                <h4 class="font-semibold text-white">Watch It Open</h4>
                                <p>The box lid will open with a smooth animation</p>
                            </div>
                        </div>

                        <div class="flex items-start">
                            <div class="bg-green-500 text-white rounded-full w-8 h-8 flex items-center justify-center font-bold mr-4 mt-1">3</div>
                            <div>
                                <h4 class="font-semibold text-white">Discover Your Prize</h4>
                                <p>A random prize will be revealed from inside the box!</p>
                            </div>
                        </div>
                    </div>

                    <!-- Available Prizes -->
                    <div class="mt-8">
                        <h4 class="text-lg font-semibold text-white mb-4">
                            <i class="fas fa-gift text-yellow-400 mr-2"></i>
                            What's Inside?
                        </h4>
                        <div id="prizesList" class="space-y-2 max-h-48 overflow-y-auto">
                            <!-- Prizes will be loaded by JavaScript -->
                            <div class="text-center py-4">
                                <div class="spinner"></div>
                                <p class="text-blue-200 mt-2">Loading prizes...</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Game Features -->
            <div class="bg-white/10 backdrop-blur-lg rounded-2xl p-8 border border-white/20 mt-8">
                <h3 class="text-2xl font-bold text-white mb-6">
                    <i class="fas fa-star text-yellow-400 mr-2"></i>
                    Mystery Box Features
                </h3>

                <div class="grid md:grid-cols-3 gap-6 text-blue-100">
                    <div class="text-center">
                        <i class="fas fa-surprise text-purple-400 text-3xl mb-3"></i>
                        <h4 class="font-semibold text-white mb-2">Element of Surprise</h4>
                        <p>You never know what amazing prize awaits inside each mystery box!</p>
                    </div>

                    <div class="text-center">
                        <i class="fas fa-balance-scale text-blue-400 text-3xl mb-3"></i>
                        <h4 class="font-semibold text-white mb-2">Fair Odds</h4>
                        <p>Each box contains a randomly selected prize with transparent probability.</p>
                    </div>

                    <div class="text-center">
                        <i class="fas fa-bolt text-yellow-400 text-3xl mb-3"></i>
                        <h4 class="font-semibold text-white mb-2">Instant Reveal</h4>
                        <p>Your prize is revealed immediately with exciting animations!</p>
                    </div>
                </div>
            </div>

            <!-- Tips -->
            <div class="bg-white/10 backdrop-blur-lg rounded-2xl p-8 border border-white/20 mt-8">
                <h3 class="text-2xl font-bold text-white mb-6">
                    <i class="fas fa-lightbulb text-yellow-400 mr-2"></i>
                    Pro Tips
                </h3>

                <div class="grid md:grid-cols-2 gap-6 text-blue-100">
                    <div>
                        <h4 class="font-semibold text-white mb-2">
                            <i class="fas fa-clock text-green-400 mr-2"></i>
                            Best Times to Play
                        </h4>
                        <p>Mystery boxes are available 24/7, so you can try your luck anytime!</p>
                    </div>

                    <div>
                        <h4 class="font-semibold text-white mb-2">
                            <i class="fas fa-chart-line text-blue-400 mr-2"></i>
                            Track Your Progress
                        </h4>
                        <p>Check your history to see all the amazing prizes you've won from mystery boxes.</p>
                    </div>

                    <div>
                        <h4 class="font-semibold text-white mb-2">
                            <i class="fas fa-gift text-purple-400 mr-2"></i>
                            Prize Variety
                        </h4>
                        <p>Mystery boxes contain the same great prizes as the wheel, just with a different experience!</p>
                    </div>

                    <div>
                        <h4 class="font-semibold text-white mb-2">
                            <i class="fas fa-mobile-alt text-pink-400 mr-2"></i>
                            Mobile Friendly
                        </h4>
                        <p>Open mystery boxes on any device - desktop, tablet, or mobile!</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <?php include 'footer.php'; ?>

    <div id="fireworks-container" style="position: fixed; top: 0; left: 0; width: 100%; height: 100%; z-index: 9999; pointer-events: none;"></div>

    <script src="/assets/js/app.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/fireworks-js@2.1.0/dist/index.umd.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/canvas-confetti@1.6.0/dist/confetti.browser.min.js"></script>

    <script>
        $(document).ready(function() {
            // Generate 5x3 grid of mystery boxes
            generateBoxGrid();

            // Load box prizes
            loadBoxPrizes();

            const container = document.getElementById('fireworks-container');
            const fireworks = new Fireworks.default(container, {
                speed: 4,
                acceleration: 1.05,
                friction: 0.98,
                gravity: 1.5,
                particles: 50,
                trace: 3,
                explosion: 5,
                intensity: 30,
                flickering: 50,
                lineStyle: 'round',
                hue: {
                    min: 0,
                    max: 360
                },
                delay: {
                    min: 15,
                    max: 30
                },
                rocketsPoint: {
                    min: 0,
                    max: 100
                },
                lineWidth: {
                    explosion: {
                        min: 1,
                        max: 3
                    },
                    trace: {
                        min: 1,
                        max: 2
                    }
                },
                brightness: {
                    min: 50,
                    max: 80
                },
                decay: {
                    min: 0.015,
                    max: 0.03
                }
            });

            $(document).on('click', '.full-screen', function() {
                toggleFullScreen();
                if ($('.hide-full').hasClass('hidden')) {
                    $('.hide-full').removeClass('hidden');
                } else {
                    $('.hide-full').addClass('hidden');
                }
            });

            function toggleFullScreen() {
                const doc = window.document;
                const docEl = doc.documentElement;

                const requestFullScreen = docEl.requestFullscreen || docEl.mozRequestFullScreen || docEl.webkitRequestFullScreen || docEl.msRequestFullscreen;
                const cancelFullScreen = doc.exitFullscreen || doc.mozCancelFullScreen || doc.webkitExitFullscreen || doc.msExitFullscreen;

                if (!doc.fullscreenElement && !doc.mozFullScreenElement && !doc.webkitFullscreenElement && !doc.msFullscreenElement) {
                    // Enter fullscreen
                    if (requestFullScreen) {
                        requestFullScreen.call(docEl);
                        $('.full-screen').html('<i class="fas fa-compress"></i> Exit Fullscreen');
                    }
                } else {
                    // Exit fullscreen
                    if (cancelFullScreen) {
                        cancelFullScreen.call(doc);
                        $('.full-screen').html('<i class="fas fa-expand"></i> Fullscreen');
                    }
                }
            }

            $(document).on('keydown', function(e) {
                if (e.key === "Escape" || e.keyCode === 27) {
                    if (document.fullscreenElement) {
                        document.exitFullscreen();
                    } else {
                        document.documentElement.requestFullscreen()
                            .catch(err => console.log("Fullscreen failed:", err));
                    }
                }
            });

            async function loadBoxPrizes() {
                try {
                    const prizes = await window.prizeApp.loadPrizes('box');

                    if (prizes && prizes.length > 0) {
                        // Update prizes list
                        updatePrizesList(prizes);
                    } else {
                        $('#prizesList').html('<div class="text-center text-blue-200">No prizes available at this time.</div>');
                        $('.mystery-box').addClass('disabled');
                    }
                } catch (error) {
                    console.error('Failed to load prizes:', error);
                    $('#prizesList').html('<div class="text-center text-red-300">Failed to load prizes. Please refresh the page.</div>');
                }
            }

            function generateBoxGrid() {
                const $grid = $('#boxGrid');
                $grid.empty();

                // Create 15 boxes (5x3 grid)
                for (let i = 0; i < 15; i++) {
                    const boxHtml = `
                        <div class="mystery-box" data-box-id="${i}">
                            <i class="fas fa-gift mystery-box-icon"></i>
                        </div>
                    `;
                    $grid.append(boxHtml);
                }

                // Add click handlers to all boxes
                $('.mystery-box').on('click', function() {
                    if (!$(this).hasClass('disabled') && !window.prizeApp.isSpinning) {
                        const boxId = $(this).data('box-id');
                        openSelectedBox($(this), boxId);
                    }
                });
            }

            var interval;

            async function openSelectedBox($box, boxId) {
                if (window.prizeApp.isSpinning) return;

                window.prizeApp.isSpinning = true;

                // Disable all other boxes
                $('.mystery-box').not($box).addClass('disabled');

                // Highlight selected box
                $box.addClass('selected');

                try {
                    // Animate box opening
                    $box.addClass('opening');

                    // Make API call to get prize
                    const response = await $.post('/api/spin.php', {
                        method: 'box'
                    });

                    if (response.success) {
                        // Show result after animation
                        setTimeout(() => {
                            window.prizeApp.showPrizeResult(response.data.prize, 'box');
                            resetBoxes();
                            // Start fireworks
                            fireworks.start();

                            // Stop after 5 seconds
                            setTimeout(() => {
                                fireworks.stop();
                            }, 5000);

                            var duration = 15 * 1000;
                            var animationEnd = Date.now() + duration;
                            var defaults = {
                                startVelocity: 30,
                                spread: 360,
                                ticks: 60,
                                zIndex: 9999
                            };

                            function randomInRange(min, max) {
                                return Math.random() * (max - min) + min;
                            }

                            interval = setInterval(function() {
                                var timeLeft = animationEnd - Date.now();

                                if (timeLeft <= 0) {
                                    return clearInterval(interval);
                                }

                                var particleCount = 50 * (timeLeft / duration);
                                // since particles fall down, start a bit higher than random
                                confetti({
                                    ...defaults,
                                    particleCount,
                                    origin: {
                                        x: randomInRange(0.1, 0.3),
                                        y: Math.random() - 0.2
                                    }
                                });
                                confetti({
                                    ...defaults,
                                    particleCount,
                                    origin: {
                                        x: randomInRange(0.7, 0.9),
                                        y: Math.random() - 0.2
                                    }
                                });
                            }, 250);
                        }, 1000);
                    } else {
                        window.prizeApp.showError(response.message || 'Failed to open box');
                        resetBoxes();
                    }
                } catch (error) {
                    window.prizeApp.showError('Network error. Please try again.');
                    resetBoxes();
                }
            }

            $(document).on('click', '.close-modal', function() {
                fireworks.stop();
                clearInterval(interval);
            });

            function resetBoxes() {
                window.prizeApp.isSpinning = false;
                $('.mystery-box').removeClass('disabled selected opening');
            }

            function updatePrizesList(prizes) {
                const $list = $('#prizesList');
                $list.empty();

                prizes.forEach(prize => {
                    const prizeItem = $(`
                        <div class="flex justify-between items-center bg-white/5 rounded-lg p-3">
                            <div>
                                <span class="text-white font-medium">${prize.name}</span>
                                <span class="text-blue-200 text-sm ml-2">(${prize.quantity} left)</span>
                            </div>
                            <div class="text-right">
                                <div class="text-green-400 font-bold">${prize.formatted_price}</div>
                                <div class="text-blue-300 text-xs">${prize.percentage}% chance</div>
                            </div>
                        </div>
                    `);
                    $list.append(prizeItem);
                });
            }
        });
    </script>
</body>

</html>